FROM armdocker.seli.gic.ericsson.se/dockerhub-ericsson-remote/nginx:1.15.12-alpine
COPY default.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html/
COPY public/* .
COPY modules/index.html .

# Copy Version for Sharing via Volume
COPY VERSION /usr/share/nginx/version-info/
